In [3]:
import pandas as pa

df = pa.read_csv('iris.csv')

df.head().T

                       0            1            2            3            4
SepalLength          5.1          4.9          4.7          4.6          5.0
SepalWidth           3.5          3.0          3.2          3.1          3.6
PedalLength          1.4          1.4          1.3          1.5          1.4
PedalWidth           0.2          0.2          0.2          0.2          0.2
Class        Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa

In [4]:
df.dtypes

SepalLength    float64
SepalWidth     float64
PedalLength    float64
PedalWidth     float64
Class           object
dtype: object

In [5]:
df['SepalLength'].mean()

5.843333333333335

In [6]:
df['SepalLength'] = df['SepalLength'].astype('int')

In [7]:
df['SepalLength'].mean()

5.386666666666667

Does converting SepalLength to integer increase or decrease the mean?

**Ans:**
If we convert the data type of sepal lenght to integer then the mean is decreased.

In [8]:
df.shift()

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0            NaN         NaN          NaN         NaN             NaN
1            5.0         3.5          1.4         0.2     Iris-setosa
2            4.0         3.0          1.4         0.2     Iris-setosa
3            4.0         3.2          1.3         0.2     Iris-setosa
4            4.0         3.1          1.5         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.0         3.3          5.7         2.5  Iris-virginica
146          6.0         3.0          5.2         2.3  Iris-virginica
147          6.0         2.5          5.0         1.9  Iris-virginica
148          6.0         3.0          5.2         2.0  Iris-virginica
149          6.0         3.4          5.4         2.3  Iris-virginica

[150 rows x 5 columns]

In [9]:
df.groupby(by=["Class"]).shift()

     SepalLength  SepalWidth  PedalLength  PedalWidth
0            NaN         NaN          NaN         NaN
1            5.0         3.5          1.4         0.2
2            4.0         3.0          1.4         0.2
3            4.0         3.2          1.3         0.2
4            4.0         3.1          1.5         0.2
..           ...         ...          ...         ...
145          6.0         3.3          5.7         2.5
146          6.0         3.0          5.2         2.3
147          6.0         2.5          5.0         1.9
148          6.0         3.0          5.2         2.0
149          6.0         3.4          5.4         2.3

[150 rows x 4 columns]

Does the direction of the shift remain the same if you groupby Class?

**Ans**
No, it remains the same in all cases.

Gather the mean, median, count and standard deviation of all columns when grouped by Class.

In [10]:
df.groupby(by=["Class"]).mean()

                 SepalLength  SepalWidth  PedalLength  PedalWidth
Class
Iris-setosa             4.60       3.418        1.464       0.244
Iris-versicolor         5.48       2.770        4.260       1.326
Iris-virginica          6.08       2.974        5.552       2.026

In [11]:
df.groupby(by=["Class"]).median()

                 SepalLength  SepalWidth  PedalLength  PedalWidth
Class
Iris-setosa              5.0         3.4         1.50         0.2
Iris-versicolor          5.0         2.8         4.35         1.3
Iris-virginica           6.0         3.0         5.55         2.0

In [12]:
df.groupby(by=["Class"]).count()

                 SepalLength  SepalWidth  PedalLength  PedalWidth
Class
Iris-setosa               50          50           50          50
Iris-versicolor           50          50           50          50
Iris-virginica            50          50           50          50

In [13]:
df.groupby(by=["Class"]).std()

                 SepalLength  SepalWidth  PedalLength  PedalWidth
Class
Iris-setosa         0.494872    0.381024     0.173511    0.107210
Iris-versicolor     0.579937    0.313798     0.469911    0.197753
Iris-virginica      0.665168    0.322497     0.551895    0.274650